// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqsRWd1RT-LyqFQIsCCAtjFJgKHGhs4nA',
    appId: '1:368293262949:web:8bb199d6fb0bb5559ff88c',
    messagingSenderId: '368293262949',
    projectId: 'devicetrustapp',
    authDomain: 'devicetrustapp.firebaseapp.com',
    databaseURL: 'https://devicetrustapp-default-rtdb.firebaseio.com',
    storageBucket: 'devicetrustapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_ktYwKy9thhR1Qx016iFhlZOtaUWTcM',
    appId: '1:368293262949:android:51e9aea035690ed89ff88c',
    messagingSenderId: '368293262949',
    projectId: 'devicetrustapp',
    databaseURL: 'https://devicetrustapp-default-rtdb.firebaseio.com',
    storageBucket: 'devicetrustapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByzBKPHpTb6oGGuUtc1vd8NEeESVLKjZw',
    appId: '1:368293262949:ios:64797de639f49c3d9ff88c',
    messagingSenderId: '368293262949',
    projectId: 'devicetrustapp',
    databaseURL: 'https://devicetrustapp-default-rtdb.firebaseio.com',
    storageBucket: 'devicetrustapp.firebasestorage.app',
    iosBundleId: 'com.example.deviceTrustApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByzBKPHpTb6oGGuUtc1vd8NEeESVLKjZw',
    appId: '1:368293262949:ios:64797de639f49c3d9ff88c',
    messagingSenderId: '368293262949',
    projectId: 'devicetrustapp',
    databaseURL: 'https://devicetrustapp-default-rtdb.firebaseio.com',
    storageBucket: 'devicetrustapp.firebasestorage.app',
    iosBundleId: 'com.example.deviceTrustApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqsRWd1RT-LyqFQIsCCAtjFJgKHGhs4nA',
    appId: '1:368293262949:web:25422d81a92f7b039ff88c',
    messagingSenderId: '368293262949',
    projectId: 'devicetrustapp',
    authDomain: 'devicetrustapp.firebaseapp.com',
    databaseURL: 'https://devicetrustapp-default-rtdb.firebaseio.com',
    storageBucket: 'devicetrustapp.firebasestorage.app',
  );
}
